# Temporarily disabled - using staging-deploy.yml instead
# name: Deploy

# on:
#   push:
#     branches:
#       - main
#     paths-ignore:
#       - '**/*.md'
#       - '.github/**'
#       - '!.github/workflows/**'
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-staging:
    name: Build for Staging
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm
        
      - name: Build for staging
        run: pnpm run build --mode staging
        env:
          VITE_SUPABASE_URL: ${{ secrets.STAGING_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.STAGING_SUPABASE_ANON_KEY }}
          
      - name: Upload staging build
        uses: actions/upload-artifact@v4
        with:
          name: staging-build
          path: |
            packages/*/dist
            packages/*/build
          retention-days: 1

  build-production:
    name: Build for Production
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm
        
      - name: Build for production
        run: pnpm run build --mode production
        env:
          VITE_SUPABASE_URL: ${{ secrets.PRODUCTION_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.PRODUCTION_SUPABASE_ANON_KEY }}
          
      - name: Upload production build
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: |
            packages/*/dist
            packages/*/build
          retention-days: 7

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build-staging
    environment:
      name: staging
      url: https://staging.clean-woodie-campus.com
    
    steps:
      - name: Download staging build
        uses: actions/download-artifact@v4
        with:
          name: staging-build
          
      - name: Deploy to staging
        run: |
          echo "Deploying to staging environment..."
          # Add actual deployment commands here
          
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [deploy-staging, build-production]
    environment:
      name: production
      url: https://clean-woodie-campus.com
    
    steps:
      - name: Download production build
        uses: actions/download-artifact@v4
        with:
          name: production-build
          
      - name: Deploy to production
        run: |
          echo "Deploying to production environment..."
          # Add actual deployment commands here