name: Staging Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Enable Corepack
      run: corepack enable
    
    - name: Setup pnpm
      run: corepack prepare pnpm@8 --activate
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Build domain package
      run: pnpm --filter @woodie/domain run build
    
    - name: Build application package  
      run: pnpm --filter @woodie/application run build
    
    - name: Build infrastructure package  
      run: pnpm --filter @woodie/infrastructure run build
    
    - name: Build web package for staging
      env:
        VITE_SUPABASE_URL: ${{ secrets.STAGING_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.STAGING_SUPABASE_ANON_KEY }}
        VITE_APP_ENV: staging
        VITE_APP_NAME: "Clean Woodie Campus (Staging)"
        VITE_ENABLE_DEV_TOOLS: true
        VITE_ENABLE_ANALYTICS: false
        # 새로 구현된 UseCase UI 표면 Feature Flags
        VITE_FEATURE_SIGNIN: true
        VITE_FEATURE_SIGNUP: true
        VITE_FEATURE_PROFILE: true
        VITE_FEATURE_REVIEW_SYSTEM: true
        VITE_FEATURE_REVIEW_STATISTICS: true
        VITE_FEATURE_CLASS_PROGRESS: true
        VITE_FEATURE_STREAK_RANKINGS: true
        VITE_FEATURE_LEADERBOARDS: true
        VITE_FEATURE_REWARDS: true
        VITE_FEATURE_TOKENS: true
        # MSW는 스테이징에서 비활성화
        VITE_MSW_ENABLED: false
        # Storybook은 스테이징에서 접근 가능
        VITE_STORYBOOK_ENABLED: true
      run: pnpm --filter @woodie/web run build --mode staging
    
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: packages/web
        vercel-args: '--prod'
    
    - name: Check build output
      run: |
        echo "Build completed successfully!"
        ls -la packages/web/dist/