name: Staging Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Enable Corepack
      run: corepack enable
    
    - name: Setup pnpm
      run: corepack prepare pnpm@8 --activate
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Build domain package
      run: pnpm --filter @woodie/domain run build
    
    - name: Build infrastructure package  
      run: pnpm --filter @woodie/infrastructure run build
    
    - name: Build web package for staging
      env:
        VITE_SUPABASE_URL: ${{ secrets.STAGING_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.STAGING_SUPABASE_ANON_KEY }}
        VITE_APP_ENV: staging
        VITE_APP_NAME: "Clean Woodie Campus (Staging)"
        VITE_ENABLE_DEV_TOOLS: true
        VITE_ENABLE_ANALYTICS: false
      run: pnpm --filter @woodie/web run build --mode staging
    
    # Temporarily disable Vercel deploy to test build only
    # - name: Deploy to Vercel
    #   uses: vercel/action@v1
    #   with:
    #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
    #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
    #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
    #     working-directory: packages/web
    #     vercel-args: '--prod --yes'
    
    - name: Check build output
      run: |
        echo "Build completed successfully!"
        ls -la packages/web/dist/